import type { PortalData } from './domain';
import { fishTypes, levelForXp } from './domain';
const names = [
  'Ada Yılmaz',
  'Deniz Kaya',
  'Ege Demir',
  'Elif Aksoy',
  'Aras Yıldız',
  'Defne Aydın',
  'Ali Çelik',
  'Duru Şahin',
  'Mert Arslan',
  'İpek Koç',
  'Can Deniz',
  'Mina Güneş',
];
export const demoData: PortalData = {
  classes: [
    {
      id: 'demo-class',
      teacher_id: 'demo-teacher',
      name: '3-A · Okyanus Kaşifleri',
      grade: '3. sınıf',
      class_xp: 1280,
      decor_level: 2,
      show_names: true,
    },
  ],
  students: names.map((name, i) => ({
    id: `demo-${i}`,
    class_id: 'demo-class',
    name,
    student_number: String(101 + i),
    photo_path: null,
    fish_type: fishTypes[i],
    xp: 120 + i * 27,
    feed: 12 + i * 3,
    level: levelForXp(120 + i * 27),
    created_at: '2026-09-01T00:00:00Z',
  })),
  tasks: [
    {
      id: 'task-1',
      class_id: 'demo-class',
      title: 'Kitabında yeni bir dünyaya dal',
      description: 'Seçtiğin kitaptan 20 sayfa oku. En sevdiğin bölümü sınıfta paylaş.',
      type: 'okuma',
      xp_reward: 40,
      feed_reward: 10,
      due_date: '2026-09-24',
    },
    {
      id: 'task-2',
      class_id: 'demo-class',
      title: 'Bir iyilik, bin dalga',
      description: 'Bugün bir arkadaşına yardım et ve deneyimini paylaş.',
      type: 'davranış',
      xp_reward: 25,
      feed_reward: 5,
      due_date: '2026-09-25',
    },
    {
      id: 'task-3',
      class_id: 'demo-class',
      title: 'Sayıların gizli hazinesi',
      description: 'Çalışma kitabındaki toplama etkinliğini tamamla.',
      type: 'ödev',
      xp_reward: 50,
      feed_reward: 15,
      due_date: '2026-09-26',
    },
  ],
  assignments: names.flatMap((_, i) =>
    [1, 2, 3].map((t) => ({
      id: `a-${i}-${t}`,
      task_id: `task-${t}`,
      student_id: `demo-${i}`,
      status: i % 4 === 0 && t === 3 ? ('pending' as const) : ('approved' as const),
      approved_at: i % 4 === 0 && t === 3 ? null : `2026-09-${14 + (i % 7)}T12:00:00Z`,
      completed_at: null,
    })),
  ),
  announcements: [
    {
      id: 'note-1',
      class_id: 'demo-class',
      title: 'Bu hafta birlikte çok yol aldık.',
      body: 'Okuma yolculuğumuz devam ediyor. Cuma günü herkes en sevdiği kitap kahramanını anlatacak. Küçük çabaların yarattığı büyük gelişimi görmek çok güzel!',
      visible_to_parents: true,
      created_at: '2026-09-20T09:00:00Z',
    },
  ],
  badges: [{ student_id: 'demo-0', badge_id: 'first-task', earned_at: '2026-09-15T00:00:00Z' }],
};
